apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "nodejs-mongodb-example", "namespace":
        "", "kind": "DeploymentConfig"}]'
    labels:
      name: sample-pipeline
      template: application-template-sample-pipeline
    name: sample-pipeline
  spec:
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          node('nodejs') {
            stage('build') {
              openshiftBuild(buildConfig: 'nodejs-mongodb-example', showBuildLogs: 'true')
            }
            stage('deploy') {
              openshiftDeploy(deploymentConfig: 'nodejs-mongodb-example')
            }
          }
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "mongodb", "namespace":
        "", "kind": "Service"}]'
    labels:
      template: application-template-sample-pipeline
    name: nodejs-mongodb-example
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: nodejs-mongodb-example
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      template: application-template-sample-pipeline
    name: nodejs-mongodb-example
  spec:
    host: ""
    to:
      kind: Service
      name: nodejs-mongodb-example
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    labels:
      template: application-template-sample-pipeline
    name: nodejs-mongodb-example
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    labels:
      template: application-template-sample-pipeline
    name: nodejs-mongodb-example
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-mongodb-example:latest
    postCommit:
      script: npm test
    source:
      contextDir: ""
      git:
        ref: ""
        uri: https://github.com/openshift/nodejs-ex.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: NPM_MIRROR
          value: ""
        from:
          kind: ImageStreamTag
          name: nodejs:4
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: u6OXFrncoPfi4XA1kyUPfW1EtFRWXgJP4g4Ua3ca
      type: GitHub
    - generic:
        secret: dYoWMBKmrLJO4MLpYDctpr6pQiJLJPnKssQF2QIN
      type: Generic
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    labels:
      template: application-template-sample-pipeline
    name: nodejs-mongodb-example
  spec:
    replicas: 1
    selector:
      name: nodejs-mongodb-example
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: nodejs-mongodb-example
        name: nodejs-mongodb-example
      spec:
        containers:
        - env:
          - name: DATABASE_SERVICE_NAME
            value: mongodb
          - name: MONGODB_USER
            value: userA2P
          - name: MONGODB_PASSWORD
            value: KfUS6wPclT74Mkcm
          - name: MONGODB_DATABASE
            value: sampledb
          - name: MONGODB_ADMIN_PASSWORD
            value: k0wcMfiNcupGIhcf
          image: ' '
          livenessProbe:
            httpGet:
              path: /pagecount
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: nodejs-mongodb-example
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /pagecount
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: 512Mi
    triggers:
    - imageChangeParams:
        automatic: false
        containerNames:
        - nodejs-mongodb-example
        from:
          kind: ImageStreamTag
          name: nodejs-mongodb-example:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the database server
    labels:
      template: application-template-sample-pipeline
    name: mongodb
  spec:
    ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
    selector:
      name: mongodb
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the database
    labels:
      template: application-template-sample-pipeline
    name: mongodb
  spec:
    replicas: 1
    selector:
      name: mongodb
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: mongodb
        name: mongodb
      spec:
        containers:
        - env:
          - name: MONGODB_USER
            value: userA2P
          - name: MONGODB_PASSWORD
            value: KfUS6wPclT74Mkcm
          - name: MONGODB_DATABASE
            value: sampledb
          - name: MONGODB_ADMIN_PASSWORD
            value: k0wcMfiNcupGIhcf
          image: ' '
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: mongodb
          ports:
          - containerPort: 27017
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            initialDelaySeconds: 3
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - mountPath: /var/lib/mongodb/data
            name: mongodb-data
        volumes:
        - emptyDir:
            medium: ""
          name: mongodb-data
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mongodb
        from:
          kind: ImageStreamTag
          name: mongodb:3.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
kind: List
metadata: {}
