apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    creationTimestamp: null
    labels:
      app: simple-node-app
    name: simple-node-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: simple-node-app:latest
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/jeckste/simple-node-app.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: NPM_MIRROR
        from:
          kind: ImageStreamTag
          name: nodejs:4
          namespace: openshift
      type: Source
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "simple-node-app", "namespace":
        "", "kind": "DeploymentConfig"}]'
    creationTimestamp: null
    labels:
      app: simple-node-app
      name: simple-node-app
    name: simple-node-app
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: None
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          node {
            stage('build') {
              openshiftBuild(buildConfig: 'simple-node-app', showBuildLogs: 'true')
            }
          }
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
  status:
    lastVersion: 0
kind: List
metadata: {}
