apiVersion: v1
kind: ImageStream
metadata:
  name: simple-node-app
  namespace: myproject
spec: {}
status:
  dockerImageRepository: '172.30.1.1:5000/myproject/simple-node-app'
  tags:
    - tag: 'latest'
