apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "simple-node-app", "namespace":
      "", "kind": "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: simple-node-app-pipeline
    name: simple-node-app-pipeline
  name: simple-node-app-pipeline
spec:
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
          stage('build') {
            openshiftBuild(buildConfig: 'simple-node-app', showBuildLogs: 'true')
          }
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
